"""Shared constants for the pitch pipeline."""

DEFAULT_ANALYSIS_FPS = 2.0
DEFAULT_CONFIDENCE_THRESHOLD = 0.5
DEFAULT_GENERATED_FRAME_COUNT = 1800
DEFAULT_GENERATED_FPS = 30.0
DEFAULT_IMAGE_HEIGHT = 720
DEFAULT_IMAGE_WIDTH = 1280
DEFAULT_JOB_ID = "local-run"
DEFAULT_MIN_FIELD_AREA = 1000.0
DEFAULT_PADDING_PX = 20
DEFAULT_PROGRESS_INTERVAL_SECONDS = 5.0
DEFAULT_REPORTING_TIMEOUT_SECONDS = 3.0
DEFAULT_VIDEO_PATH = "synthetic_pitch_feed.mp4"
MASK_DETECTOR_TYPE = "sam_mask_v1"
SUPPORTED_ASPECT_RATIO = "16:9"
SUPPORTED_SPORT = "football"

